name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
                    
        test:
            
            name: Test Codebase
            runs-on: ubuntu-latest
        
            steps:
        
              - name: Checkout
                id: checkout
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
            
              - name: Version
                id: version
                run: echo "${{ github.event.pull_request.head.ref }}" | perl -nle 'm/feature\/(\d+\.\d+\.\d+)/; print "number=",$1' >> "$GITHUB_OUTPUT"
            
              - name: Check Changelog
                id: changelog
                if: ${{ steps.version.outputs.number != '' }}
                run: echo "count="$(cat CHANGELOG.md | grep -E -c "## v${{ steps.version.outputs.number }}") >> "$GITHUB_OUTPUT"
                
              - name: Changelog Test
                id: test
                if: ${{ steps.version.outputs.number != '' && steps.changelog.outputs.count != 1 }}
                run: echo "Found ${{ steps.changelog.outputs.count }} changelog lines for version ${{ steps.version.outputs.number }} in CHANGELOG.md"; exit 1
