name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
                    
        setup:
            name: Setup
            runs-on: ubuntu-latest
            outputs:
                version: ${{ steps.version.number }}
            steps:
            
              - name: Version
                id: version
                run: echo "${{ github.event.pull_request.head.ref }}" | perl -nle 'm/feature\/(\d+\.\d+\.\d+)/; print "number=",$1' >> "$GITHUB_OUTPUT"
        
        test:
            name: Test Versioning
            runs-on: ubuntu-latest
            needs: setup
            if: needs.setup.outputs.version != ''
            steps:
        
              - name: Checkout
                id: checkout
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
            
              - name: Check Changelog
                id: changelog
                run: echo "count="$(cat CHANGELOG.md | grep -E -c "## v${{ steps.version.outputs.number }}") >> "$GITHUB_OUTPUT"
                
              - name: Changelog Test
                id: test
                if: ${{ steps.changelog.outputs.count != 1 }}
                run: echo "Found ${{ steps.changelog.outputs.count }} changelog lines for version ${{ needs.setup.outputs.version }} in CHANGELOG.md"; exit 1
                
              - name: Git Tag
                id: tag
                run: git tag ${{ needs.setup.outputs.version }}; git push --force
                
            # name: Publish Release
            # on:
            #   push:
            #     tags:
            #       - 'v*'
            # jobs:
            #   build:
            #     runs-on: ubuntu-latest
            #     steps:
            #     - uses: actions/checkout@v3
            #     - name: Create a Release
            #       uses: elgohr/Github-Release-Action@v4
            #       env:
            #         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
            #       with:
            #         title: MyReleaseMessage
